### PR TITLE
Flaky test: Remove Imported Cluster

### LINKED ISSUE #381: Flaky test: Remove Imported Cluster
```

  2) Import CAPV RKE2 Class-Cluster
       [TEARDOWN]
         Remove imported CAPV cluster from Rancher Manager:
     AssertionError: Timed out retrying after 30000ms: Expected to find element: `[data-testid=sortable-table-promptRemove]`, but never found it.
      at Context.eval (webpack://rancher-turtles-e2e/./node_modules/@rancher-ecp-qa/cypress-library/index.ts:304:0)
      at wrapped (https://10.124.139.176.sslip.io/__cypress/runner/cypress_runner.js:141525:43)

```

```
  2) Import CAPA RKE2 Class-Cluster
       [TEARDOWN]
         Remove imported CAPA cluster from Rancher Manager:
     CypressError: Timed out retrying after 30050ms: `cy.click()` failed because this element is `disabled`:

`<button data-v-023e75ee="" id="promptRemove" type="button" class="btn role-primary bulk-action" disabled="" data-testid="sortable-table-promptRemove" role="button" aria-label="Delete" style="display: inline-flex;">...</button>`

Fix this problem, or use `***force: true***` to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at Object.isNotDisabled (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:148336:58)
      at runAllChecks (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:114544:26)
      at retryActionability (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:114633:16)
      at tryCatcher (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:1777:23)
      at Promise.attempt.Promise.try (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:4285:29)
      at whenStable (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:147197:68)
      at <unknown> (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:147138:14)
      at tryCatcher (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:1777:23)
      at Promise._settlePromiseFromHandler (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:1489:31)
      at Promise._settlePromise (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:1546:18)
      at Promise._settlePromise0 (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:1591:10)
      at Promise._settlePromises (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:1671:18)
      at Promise._fulfill (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:1615:18)
      at <unknown> (https://60.211.47.34.bc.googleusercontent.com/__cypress/runner/cypress_runner.js:5420:46)



[mochawesome] Report JSON saved to /workdir/cypress/reports/html/.jsons/mochawesome_005.json
```

This test has been failing more than it has been passing.

Recent failure short runs: https://github.com/rancher/rancher-turtles-e2e/actions/runs/20420876875/job/58672142385
long runs: https://github.com/rancher/rancher-turtles-e2e/actions/runs/20389580423/job/58596752976
vsphere runs (passed: 1, failed: 1) : https://github.com/rancher/rancher-turtles-e2e/actions/runs/20421619372/job/58674425385

### PR DESCRIPTION
**Pull request by valaparthvi**
### What does this PR do?
1. Move `Remove Imported CAPI Cluster from Rancher Manager` test to [CLUSTER-OPERATIONS] so it will only be run if the cluster is imported.
2. Remove `cluster-name` from GH action input since it is unused.
3. Use `github_runner.number` for artifact names to easily identify the resource with it's GH action.
image

4. Use `cy.task('log', message)` instead of `cy.log(message)` to show details on terminal.
image

### Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #381 

### Checklist:
- [ ] Squashed commits into logical changes
- [ ] Documentation
- [x] GitHub Actions (if applicable) -[short](https://github.com/rancher/rancher-turtles-e2e/actions/runs/20486710439), [full](https://github.com/rancher/rancher-turtles-e2e/actions/runs/20486710439)

### CODE REVIEW

File: tests/cypress/latest/support/e2e.ts [hunk 1]
```diff
@@ -125,30 +125,30 @@ before(function () {
...
-    cy.log('Running in GitHub Actions - checking previous test result');
+    cy.task('log', 'Running in GitHub Actions - checking previous test result');
     cy.readFile(resultFile).then((data) => {
       const content = yaml.load(data)
       const result = content['test_result']
       const stop_cypress = content['stop_cypress']
       const skip_all_tests = content['skip_all_tests']
       const run_delete_tests = content['run_delete_tests']
-      cy.log('Previous Test Result: ' + content);
+      cy.task('log', 'Previous Test Result: ' + content);
```
Comment (cpinjani) [inline tests/cypress/latest/support/e2e.ts]: Its logging as below, not sure if it was same before this change.
`Previous Test Result: [object Object]`

**Comment by valaparthvi** [comment]
latest short run: https://github.com/rancher/rancher-turtles-e2e/actions/runs/20519256460/job/58951847292#step:21:437

image

**Comment by cpinjani** [comment]
> latest short run: [rancher/rancher-turtles-e2e/actions/runs/20519256460/job/58951847292#step:21:437](https://github.com/rancher/rancher-turtles-e2e/actions/runs/20519256460/job/58951847292#step:21:437)
> 
> image

Thanks for fixing it. But it appears that there is way too much logging and duplication on console, wdyt ? 

image

**Comment by valaparthvi** [comment]
latest run - https://github.com/rancher/rancher-turtles-e2e/actions/runs/20521012382

**Review by cpinjani — APPROVED** [review]
