### PR TITLE
Fix failure with deploy-chartmuseum script for upgrade tests and attempt at fixing flaky tests

### LINKED ISSUE #324: Flaky behavior while selecting cluster for App Installation
Automation is unable to select the cluster installing app.

Image

https://github.com/user-attachments/assets/901345a6-e07d-4938-b445-4d97acff45f5

### LINKED ISSUE #325: Flaky behavior with Remove imported CAPX cluster from Rancher Manager
We use `cy.getBySel('sortable-table-promptRemove').click({ctrlKey: true}); // this will prevent to display confirmation dialog` to remove the cluster which can sometimes fail.

### PR DESCRIPTION
**Pull request by valaparthvi**
### What does this PR do?
1. Fix `deploy-chartmuseum` script for upgrade tests
2. Attempt at fixing removal of imported clusters.
3. Add `retries: 1` to install app tests.
4. Fix flake with Turtles UI extension installation.
5. Fix flake with app installation test on `.nav` not found. I think the error sometimes occurs because automation finds 2 instances of clusterName and cannot decide which one to select.

### Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #325 
Fixes #324 

### Checklist:
- [ ] Squashed commits into logical changes
- [ ] Documentation
- [x] GitHub Actions (if applicable) - [Fix 1](https://github.com/rancher/rancher-turtles-e2e/actions/runs/18800670925), [Fix 2 short](https://github.com/rancher/rancher-turtles-e2e/actions/runs/18801773348), [Fix 2 long](https://github.com/rancher/rancher-turtles-e2e/actions/runs/18815898645/job/53684179945)

### CODE REVIEW

File: tests/cypress/latest/support/commands.ts [hunk 1]
```diff
@@ -785,7 +791,9 @@ Cypress.Commands.add('deleteCluster', (clusterName, timeout = 120000) => {
   cy.searchCluster(clusterName);
   cy.viewport(1920, 1080);
   cy.getBySel('sortable-table_check_select_all').click();
-  cy.getBySel('sortable-table-promptRemove').click({ctrlKey: true}); // this will prevent to display confirmation dialog
+  cy.getBySel('sortable-table-promptRemove').click(); // this will prevent to display confirmation dialog
```
Comment (cpinjani) [inline tests/cypress/latest/support/commands.ts]:
```suggestion
  cy.getBySel('sortable-table-promptRemove').click();
```

**Review by cpinjani — APPROVED** [review]
lgtm
